"use strict";
console.log("The code never sleeps");
let v = 1;
v = v + 1;
console.log(v);
let a = [7, true, "hello"];
console.log(a[1]);
const b = 1;
console.log(b);
let x = 4;
let y = 3;
let temp;
console.log(x);
console.log(y);
temp = y;
y = x;
x = temp;
console.log(x);
console.log(y);
